#!/usr/bin/env python3
"""
Build crissyFieldTerrain.js: an elevation grid around Crissy Field.

Elevations come from the AWS Terrain Tiles (Terrarium encoding, derived from
USGS 3DEP and other public sources): https://registry.opendata.aws/terrain-tiles/

The grid is rectilinear with fine spacing around Crissy Field, Fort Point and the
Golden Gate Bridge, growing coarser toward Mt. Tamalpais and the edges.
Coordinates are feet relative to the installation center; x = east, z = south.

Usage: python3 scripts/build_crissy_terrain.py   (needs numpy and Pillow)
"""
import base64
import math
import os
import urllib.request

import numpy as np
from PIL import Image

LAT0, LON0 = 37.8047, -122.4628          # must match SITES['crissy-field'] in sites.js
FT_PER_DEG_LAT = 364285
FT_PER_DEG_LON = 111320 * math.cos(math.radians(LAT0)) * 3.28084
ZOOM = 13
CACHE = os.path.join(os.path.dirname(__file__), '.tile-cache')
OUTPUT = os.path.join(os.path.dirname(__file__), '..', 'crissyFieldTerrain.js')

EXTENT = {'minX': -48000, 'maxX': 40000, 'minZ': -48000, 'maxZ': 30000}
CORE = {'minX': -7000, 'maxX': 5000, 'minZ': -11000, 'maxZ': 3000}
CORE_SPACING = 80      # feet
GROWTH = 1.08          # spacing growth per line outside the core
MAX_SPACING = 1000     # feet


def axis(lo, hi, core_lo, core_hi):
    """Grid lines: uniform in the core, growing geometrically toward the edges."""
    core = list(np.arange(core_lo, core_hi + 1e-6, CORE_SPACING))
    outward = []
    for direction, limit in ((-1, lo), (1, hi)):
        lines, value, step = [], core[0] if direction < 0 else core[-1], CORE_SPACING
        while True:
            step = min(step * GROWTH, MAX_SPACING)
            value += direction * step
            if (value < limit) if direction < 0 else (value > limit):
                lines.append(limit)
                break
            lines.append(value)
        outward.append(lines)
    return [round(v) for v in list(reversed(outward[0])) + core + outward[1]]


def to_lat_lon(x, z):
    return LAT0 - z / FT_PER_DEG_LAT, LON0 + x / FT_PER_DEG_LON


def tile_coords(lat, lon):
    n = 2 ** ZOOM
    return (lon + 180) / 360 * n, (1 - math.asinh(math.tan(math.radians(lat))) / math.pi) / 2 * n


def load_mosaic():
    north_west = tile_coords(*to_lat_lon(EXTENT['minX'], EXTENT['minZ']))
    south_east = tile_coords(*to_lat_lon(EXTENT['maxX'], EXTENT['maxZ']))
    tiles_x = range(int(north_west[0]), int(south_east[0]) + 1)
    tiles_y = range(int(north_west[1]), int(south_east[1]) + 1)
    os.makedirs(CACHE, exist_ok=True)
    mosaic = np.zeros((len(tiles_y) * 256, len(tiles_x) * 256), dtype=np.float32)
    for j, ty in enumerate(tiles_y):
        for i, tx in enumerate(tiles_x):
            path = os.path.join(CACHE, f'{ZOOM}_{tx}_{ty}.png')
            if not os.path.exists(path):
                url = f'https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{ZOOM}/{tx}/{ty}.png'
                urllib.request.urlretrieve(url, path)
            rgb = np.asarray(Image.open(path).convert('RGB')).astype(np.float32)
            meters = rgb[:, :, 0] * 256 + rgb[:, :, 1] + rgb[:, :, 2] / 256 - 32768
            mosaic[j * 256:(j + 1) * 256, i * 256:(i + 1) * 256] = meters
    return mosaic, tiles_x[0], tiles_y[0]


def main():
    mosaic, tile_x0, tile_y0 = load_mosaic()

    def elevation_ft(x, z):
        tx, ty = tile_coords(*to_lat_lon(x, z))
        px, py = (tx - tile_x0) * 256 - 0.5, (ty - tile_y0) * 256 - 0.5
        x0, y0 = int(math.floor(px)), int(math.floor(py))
        fx, fy = px - x0, py - y0
        m = mosaic
        meters = (m[y0, x0] * (1 - fx) * (1 - fy) + m[y0, x0 + 1] * fx * (1 - fy) +
                  m[y0 + 1, x0] * (1 - fx) * fy + m[y0 + 1, x0 + 1] * fx * fy)
        return meters * 3.28084

    xs = axis(EXTENT['minX'], EXTENT['maxX'], CORE['minX'], CORE['maxX'])
    zs = axis(EXTENT['minZ'], EXTENT['maxZ'], CORE['minZ'], CORE['maxZ'])
    heights = np.array([[elevation_ft(x, z) for x in xs] for z in zs])
    encoded = base64.b64encode(np.round(heights).astype('<i2').tobytes()).decode('ascii')

    with open(OUTPUT, 'w') as f:
        f.write('// Generated by scripts/build_crissy_terrain.py. Do not edit by hand.\n')
        f.write('// Elevations: AWS Terrain Tiles (Terrarium), from USGS 3DEP and other public sources.\n')
        f.write('// Feet above sea level on a rectilinear grid; row-major by z, then x.\n')
        f.write('export const CRISSY_FIELD_TERRAIN = {\n')
        f.write(f'    xs: {xs},\n')
        f.write(f'    zs: {zs},\n')
        f.write(f"    heights: '{encoded}'\n")
        f.write('};\n')
    print(f'{len(xs)} x {len(zs)} grid, {os.path.getsize(OUTPUT) / 1024:.0f} KB -> {os.path.relpath(OUTPUT)}')


if __name__ == '__main__':
    main()
